theme: jekyll-theme-cayman
title: Sidereal Research
description: 
        <a href="{{ https://omoreira.github.io/siderealresearch.github.io/research }}" class="btn">Sidereal Research Lab</a>
        <a href="{{ https://omoreira.github.io/siderealresearch.github.io/publishing }}" class="btn">Sidereal Research Lab</a>
        <a href="{{ https://omoreira.github.io/siderealresearch.github.io/outreach }}" class="btn">Sidereal Science Outreach Lab</a>
        <br>
        We will be up and running soon. Thank you for your patience!
