theme: jekyll-theme-cayman
title: Sidereal Research
description: 
        We will be up and running soon. Thank you for your patience!
        <br><br>
        <a href="{{ https://omoreira.github.io/siderealresearch.github.io/research }}" class="btn">Sidereal Research Lab</a>
        <a href="{{ https://omoreira.github.io/siderealresearch.github.io/publishing }}" class="btn">Sidereal Research Lab</a>
        <a href="{{ https://omoreira.github.io/siderealresearch.github.io/outreach }}" class="btn">Sidereal Science Outreach Lab</a>
        <br>
layout: _layout/default.html
        
