title: Sidereal Research
description: We will be up and running soon. Thank you for your patience!
show_downloads: false
google_analytics:
github:
  repository_url:
  research_url: 
  outreach_url:
  repository_url:
  zip_url: 
  tar_url: 
theme: jekyll-theme-cayman

        
